Beer detail1
develhope/team-1-choose-your-own-beer pull request #61
Opened 2022-05-24 16:24 UTC by Mich9419

Delete Hardcoded.

2022-05-25 16:22 UTC, Matteo-Catalano reviewed
<img width="293" alt="Schermata 2022-05-25 alle 18 21 36" src="https://user-images.githubusercontent.com/101358401/170311714-ac63e972-ca55-4e67-8baf-81c80cc809d8.png">

2022-05-25 16:22 UTC, Matteo-Catalano commented on app/src/main/res/layout/beer_detail.xml
> +    android:layout_marginLeft="0dp"
Così non hai margine, credo tu debba aggiungere questo valore nella sezione value/dimens così poi la possiamo riutilizzare se cambia lo schermo

2022-05-25 16:22 UTC, Matteo-Catalano commented on app/src/main/res/layout/beer_detail.xml
> +        android:layout_height="37dp"
Qua vale come prima:
credo tu debba aggiungere questo valore nella sezione value/dimens così poi la possiamo riutilizzare se cambia lo schermo

2022-05-30 07:19 UTC, vincenzocostagliola requested changes
Non ho capito se pr serva ancora o meno. Inserisco un change request per evitare che erroneamente vada in merge prima di discuterla

2022-05-30 10:59 UTC, closed without merging